baseurl = "http://username.github.io"
languageCode = "en-us"
title = "makeitso.de"
theme = "beautifulhugo"
pygmentsUseClasses = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  logo = "img/path.jpg"
  subtitle = "Mathe und Physik"

[Author]
  name = "Jürgen Klein"
  email = "jklein@makeitso.de"
#  facebook = "username"
#  github = "username"
#  twitter = "username"
#  linkedin = "pub/username/X/YYY/ZZZ"
#  stackoverflow = "XXXXXXX/username"
#  soundcloud = "username"
#  wikipedia = "username"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Page"
    url = "/page"
    weight = 2
